modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/Mrbysco/Headlight/issues"
license="MIT"

[[mods]]
modId="headlight"
version="${file.jarVersion}"
displayName="Headlight"
displayURL="https://www.curseforge.com/minecraft/mc-mods/headlight"
authors="Mrbysco, ShyNieke"
description='''
Adds a helmet that stores a light source, keeping the darkness away while you explore
'''

[[dependencies.headlight]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"