modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/Headlight/issues"
license="MIT"

[[mods]]
modId="headlight"
version="${file.jarVersion}"
displayName="Headlight"
displayURL="https://www.curseforge.com/minecraft/mc-mods/headlight"
authors="Mrbysco, ShyNieke"
description='''
Adds a helmet that stores a light source, keeping the darkness away while you explore
'''

[[dependencies.headlight]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.headlight]]
modId="neoforge"
type="required"
versionRange="[21.1.1,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config="headlight.mixins.json"
[[mixins]]
config="compat.headlight.mixins.json"